### ISSUE TITLE
Error when first unit with plate on it comes into view

### ISSUE THREAD

**Issue by joeytwoshirts** [Binbwen/tidyplates#3]
I have determined that this has to do with interaction with SpartanUI
If I shut off spartanui I do not get this error.

Message: ..\AddOns\TidyPlates\TidyPlatesCore.lua line 948:
   attempt to index a nil value
Debug:
   TidyPlates\TidyPlatesCore.lua:948: ?()
   TidyPlates\TidyPlatesCore.lua:917:
      TidyPlates\TidyPlatesCore.lua:916
Locals:
self = "NAME_PLATE_UNIT_ADDED"
unitid = "nameplate1"
plate = NamePlate1 {
 0 = <userdata>
 driverFrame = NamePlateDriverFrame {
 }
 GetPreferredInsets = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:403

**Comment by Binbwen** [comment]
Thanks for the report; I've made a fix, and it'll be in the next update.

**Comment by joeytwoshirts** [comment]
Awesome, thanks for all the work. Nice addon.
