### ISSUE TITLE
Quest Mobs

### ISSUE THREAD

**Issue by theCorndog** [Binbwen/tidyplates#8]
I noticed recently that Quest Mobs are now included when filtering out Inactive Mobs. I'd like to request that functionality to return as it is one of the main reasons I use TidyPlates over any other name plates adddon.

**Comment by Binbwen** [comment]
It's coming back in, don't worry.

It needed a little tweaking - In instances, many mobs are quest mobs, which leads to a bit of unintended clutter.

The two choices:  Put a checkbox under 'Filter' to "Exclude (Show) Quest Mobs" in Filter, or add IsInInstance() check to the QuestMob check.  Leaning toward the latter.

**Comment by Binbwen** [comment]
Got a little sidetracked with family life, but I did get back to this!

**Comment by Binbwen** [comment]
Added an IsInInstance() to questmob check filter.  v6.19.3
